// Legacy helper for older pages.
// Amplify Gen 2 uses amplify_outputs.json, generated by `npx ampx sandbox`
// locally or by Amplify Hosting during CI/CD. Do not paste Cognito IDs here.

window.SUMMIT_AMPLIFY_CONFIG_PATHS = [
  '/amplify_outputs.json',
  '/amplifyconfiguration.json',
];
